########################
#  CONFIG GENERAL APP  #
########################
parameters:
    # GRAPHIQUE
    app.width: 980 #Tablet 660, 1200,... min = 655   
    app.page_color: "#F5F5F5"
    app.charte: 1
    app.version: 2.52
    app.type: "r" 
    # app.type une des valeurs suivantes [ 'a/A'=>alpha , 'b/B'=> beta , 'r/R'=>release candidate ] => influt sur l'icone à coté du titre    
    app.reload_menus_all_page: false
    app.reload_contacts_all_page: false
    app.forceAuthentification: true
    app.need_authentificate_message: "<center><div style='padding:50px;'><div class='ui-state-active ui-corner-all' style='padding:25px;text-align:left;'><center>Pour accéder à cette application, vous devez être authentifié...</center></br><p class='TabInfos' style='color:black;font-weight:normal;'><u><b>Procédure à suivre :</b></u><br>Veuillez cliquer sur le cadenas dans la barre supérieure de la page,</br>puis saisir votre couple identifiant/mot de passe dans la fenêtre centrale...<p></div></div></center>"
    app.no_access_message: "<center><div style='padding:50px;'><div class='ui-state-error ui-corner-all' style='padding:50px;text-align:left;'><center><h1>L'accès à cette page vous a été refusé.</h1></center></br><p class='TabInfos' style='color:black;'><br><b>Code:</b> #err_code#</br><b>Message:</b> #err_msg#</br><p></div></div></center>"
    
     # CAS 
    app.cas.server: "ident.univ-amu.fr"
    app.cas.port: 443
    app.cas.root: "/cas"
    app.cas.version: "2.0"
    # app.cas.version: '1.0' , '2.0' ou '3.0';
    app.cas.trace: false
    # app.cas.trace: false(défaut)/true/array ['mon_login',127.0.0.1] => active les traces sur l'autentification CAS.
    app.cas.logger: monolog.logger.cas
    # app.cas.logger => personnalisation de la classe du logger, valeurs possibles :
    #  - "monolog.logger.cas" (par défaut) => sépare/inscrit les infos de debug CAS dans un fichier spécifique (%env%_cas.log = personalisable dans config.yml)
    #  - "logger", false ou ""    =>  les fichiers logs standards seront utilisés (dev.log / prod.log) 

    # EXTERNAL APPS/TOOLS LINKS
    app.awstats: "http://dev-web.univ-amu.fr/cgi-bin/awstats.pl?config=application.univ-amu.fr"
    app.help_url: "http://dud.univ-amu.fr/content/dud-documentation-utilisateur-dynamique"
    app.groups_manager: "https://grouper.univ-amu.fr/ESCOGrouper/stylesheets/welcome.jsf"
    app.wiki_dev_docs: "http://projets-dev.univ-amu.fr/projects/symfony211/wiki/Index"
    app.phpMyAdmin: "http://dev-web.univ-amu.fr/~phpmyadmin/phpMyAd/"
    app.phpLDAPadmin: "http://dev-web.univ-amu.fr/~phpldapadmin/phpldapadmin/"
    
    # WEB SERVICES : Apogee, Harpege, BV
    ws.apogee.url: "http://apo-ws.univ-amu.fr:8888/apo-webservices/services/"
    ws.harpege.url: "http://195.221.209.65:8082/HarpegeWebService/services/"
    xmlrpc.bv.server: "bv.unr-paca.fr"
    xmlrpc.bv.port: 443
    xmlrpc.bv.user: "u3.u3admin"
    xmlrpc.bv.pass: "bv-ie1xdlo!" 
    
    # DEBUG
    app.active_trace: false
    # active les traces sur AppListener & ConfigListener
    
    # DIVERS
    # app.ldap_group_access: permet de limité l'accès à l'application 
    # (positionne app.isUserMember à "1" si l'utilisateur authentifié fait partie du groupe
    app.ldap_group_access: "amu:glob:ldap:personnel"
    app.cron.user: "www-data"
    app.rss: true
    app.show_yml_configs: true
    app.use_ext_accounts: false

    # MAINTENANCES
    app.maintenance: false
    # Pour forcer l'application en mode maintenance forcé 'app.maintenance:true' par defaut=false
    app.maintenances: false
    # Valeurs possibles pour "app.maintenances": false/true (true = activer les fonctionnalités de Maintenance via BDD APP_MAINTENANCES)
    app.maintenances_users: ["ROLE_DEVELOPPER", "127.0.0.1", "mubeda", "login_betatesteur_1", "login_betatesteur_2"]
    app.maintenance.message: "<hr>Bonjour, l'application est actuellement en cours de maintenance.</br> merci de votre compréhension."
    app.maintenance.icon: "bundles/app/images/maintenance.gif"
    
    # CAMPAGNES
    app.campagnes: false
    # Valeurs possibles pour "app.campagnes": false/true       
    app.no_campagnes_users: [ "127.0.0.1", "mubeda", "ROLE_ADMIN"]


    # MESSAGES & NOTIFICATIONS
    app.messages: false    
    # app.messages active/désactive la gestion des Messages applicatifs par le Manager (MENU+BDD)
    app.flash: true
    app.flash.opacity: 99 #97
    app.notifications: "symfony"
    # ATTENTION : Si app.notifications: "jgrowl" => n'oubliez pas de d'activer cdn.yml les librairies nécessaires ["jgrowl"]
    # app.notifications : "symfony", "" , "jgrowl" ou false
    app.notifications_timeout: 5000
    ## notifications_timeout = si autoclose valeur en ms
    app.crud_notify: true
    
##############
#   HEADER   #
##############
    app.tools_links: ['site', 'intramu', 'ent', 'annuaire', 'cas_logout']
    app.titleLogo: "bundles/app/images/ico/48/terre.png"
    # 48x48 ou 64x64 max
    app.background: "bundles/app/images/amu/fond_standard.png"
    # Autres valeurs possibles :
      # "bundles/app/images/amu/fond_dosi_social.png"
      # "bundles/app/images/amu/fond_standard.png"
    app.title: "CliGrouper"
    app.name: "CliGrouper"
    app.slogan: "Application de gestion des groupes LDAP"
    app.sm_iconizeTitleSlogan: false #Mettre (en mode sm 'SMartphone'), le nom et le slogan de l'application dans une icone/tips
    app.logo: "web/picture/logo.png"
    app.menu_min_width: false 
    # charte AMU => app.menu_min_width: 250
    app.menu_force_upper: false
    # charte AMU => app.menu_force_upper: true
    app.front_end: true
    app.back_end: true
    app.welcome: "Bienvenue sur l'application."
    app.logon_tip: "<font color=red><center><b><u>Attention</u></b></center>Vous n'êtes <i>pas encore authentifiés...</i></font><br><br>Veuillez cliquer ici, pour saisir vos identifiants de connection."
    app.logout_tip: "Vous êtes actuellement <font color=green><b>authentifiés</b></font>.<br>en tant que '<b>%s</b>'.</br></br> Si vous désirez vous déconnecter : cliquez sur le cadenas."
    app.ent: false
    # si =true => on MASQUE l entete... (cas des application "embedded"
    app.effects: true
    app.flags: 
#       - { into: "app_name", value: "<font color=green><i>DÉMO</i></font>", routes: ["/demo/*"], roles:[] }
#       - { into: "app_name", value: "<font color=red>[Admin]</font>", routes: [], roles:["ROLE_ADMIN","ROLE_SUPER_ADMIN"] }
#       - { into: "app_slogan", value: "<font color=orange><b>Accès STUDENT</b></font>", routes: ["/demo/student*"], roles:[] }
#       - { into: "app_slogan", value: "<font color=blue><b>Accès PERSONAL</b></font>", routes: ["/demo/personal*"], roles:[] }
        - { into: "app_name", value: "<font color=green>[Gestionnaire]</font>", routes: [], roles:["ROLE_GESTIONNAIRE"] }
        - { into: "app_name", value: "<font color=orange>[DOSI]</font>", routes: [], roles:["ROLE_DOSI"] }
        - { into: "app_name", value: "<font color=red>[Admin]</font>", routes: [], roles:["ROLE_SUPER_ADMIN"] }

      
##############
#   FOOTER   #
##############
    app.support: "peggy.fernandez-blanco@univ-amu.fr"
    app.footerInfos:
        - { key: 0, color: "", label: "Contacts : ", name: "Peggy Fernandez", tips: "", link: "mailto:peggy.fernandez-blanco@univ-amu.fr" }
        #- { key: 1, color: "red", label: "Aix: ", name: "Mme Untel", tips: "exemple d'informations...", link: "mailto:madame.untel@univ-amu.fr" }
        #- { key: 2, color: "green",  label: "Marseille: ", name: "M. Dupond ", tips: "exemple d'informations...2", link: "mailto:monsieur.dupond@univ-amu.fr" }
        #- { key: 3, color: "red",  label: "Contact: ", name: "Admin ", tips: "exemple d'informations...3", link: "mailto:admin@univ-amu.fr", show_roles: [ROLE_ADMIN,ROLE_SUPER_ADMIN], show_routes:["_demo_student"] }
        #- { key: 4, color: "red",  label: "Contact2: ", name: "SUPER Admin ", tips: "exemple d'informations...4", link: "mailto:super-admin@univ-amu.fr", show_roles: [ROLE_SUPER_ADMIN], show_routes:["_demo_student","_demo_personal"] }
        
    app.authors: 
       - { name: "Peggy FERNANDEZ",  mail: "peggy.fernandez-blanco@univ-amu.fr", isMain: true }
       #- { ... }


#################
#  GLOBAL TWIG  #
#################
twig:
     globals:
         app_background: %app.background%
         app_tools_links: %app.tools_links%
         app_charte: %app.charte%
         app_version: %app.version%
         app_type: %app.type%
         app_help_url: %app.help_url%
         app_rss: %app.rss%
         app_front_end: %app.front_end%
         app_back_end: %app.back_end%
         app_awstats: %app.awstats%
         app_use_cdn: %app.use_cdn%
         app_cdn_links: %app.cdn%
         app_use_ext_accounts: %app.use_ext_accounts%
         app_title: %app.title%
         app_titleLogo: %app.titleLogo%
         app_name: %app.name%
         app_slogan: %app.slogan%
         app_logo: %app.logo%
         app_logon_tip: %app.logon_tip%
         app_logout_tip: %app.logout_tip%
         app_ent: %app.ent%
         app_footer: %app.footerInfos%
         app_authors: %app.authors%
         app_forceAuthentification: %app.forceAuthentification%
         app_maintenances: %app.maintenances%  
         app_maintenance_message: %app.maintenance.message%
         app_maintenance_icon: %app.maintenance.icon%
         app_flash_opacity: %app.flash.opacity%
         app_flash: %app.flash%
         app_campagnes: %app.campagnes%  
         app_flags: %app.flags%
         app_messages: %app.messages%
         app_need_authentificate_message: %app.need_authentificate_message%
         app_effects: %app.effects%
         app_welcome: %app.welcome%
         app_no_access_message: %app.no_access_message%
         app_reload_menus_all_page: %app.reload_menus_all_page%
         app_reload_contacts_all_page: %app.reload_contacts_all_page%
         app_background: %app.background%
         app_no_campagnes_users: %app.no_campagnes_users%    
         app_width: %app.width%
         app_page_color: %app.page_color%
         app_env: %kernel.environment%
         app_menu_force_upper: %app.menu_force_upper%
         app_menu_min_width: %app.menu_min_width%
         app_sm_iconizeTitleSlogan: %app.sm_iconizeTitleSlogan%
         app_notifications: %app.notifications%   
         app_notifications_timeout: %app.notifications_timeout%
         app_crud_notify: %app.crud_notify%
         app_groups_manager: %app.groups_manager%
         app_wiki_dev_docs: %app.wiki_dev_docs%
         app_phpMyAdmin: %app.phpMyAdmin%
         app_phpLDAPadmin: %app.phpLDAPadmin%