imports:
    - { resource: parameters.yml }
    - { resource: cdn.yml }
    - { resource: app.yml }
    - { resource: menus.yml }
    - { resource: roles.yml }
    - { resource: ckeditor.yml }
    - { resource: "@AppBundle/Resources/config/amu.yml" }
    - { resource: betatesteurs.yml }
    - { resource: security.yml }

    
framework:
#    esi:
#        enabled false
    translator:      { fallback: fr }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'], hinclude_default_template: AppBundle::layout.html.twig }
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
#    fragments:
#      enabled: true
#      path: /_fragment
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: 
          - 'AppBundle:Form:amu_form_table_layout.html.twig'
          #['amu_form_table_layout.html.twig']
          
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [AppBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"


# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
#
#services:
#    twig.extension.text:
#       class: Twig_Extensions_Extension_Text
#       tags:
#           - { name: twig.extension }
# 
#    twig.extension.intl:
#       class: Twig_Extensions_Extension_Intl
#       tags:
#           - { name: twig.extension }
# 
#    debug.twig.extension:
#        class: Twig_Extensions_Extension_Debug
#        tags: [{ name: 'twig.extension' }]

services:
    CliGrouper.ldap:
        class:         Amu\CliGrouperBundle\Service\Ldap
        arguments:    [@service_container, @logger]