#############
#   MENUS   #
#############
parameters:
    menus:

#        - { key: 1, name: "Accueil", roles: ["ROLE_GESTIONNAIRE", "ROLE_DOSI"], route: "accueil", fils: false, description: "", ico: "bundles/app/images/ico/16/home.png" }
        - { key: 1, name: "Accueil", roles: ["ROLE_GESTIONNAIRE", "ROLE_DOSI"], route: "", fils: [11, 12], description: "", ico: "bundles/app/images/ico/16/home.png" }
        - { key: 11, name: "Voir mes groupes", roles: ["ROLE_GESTIONNAIRE", "ROLE_DOSI"], route: "mes_groupes", fils: false, description: "" }
        - { key: 12, name: "Voir tous les groupes", roles: ["ROLE_DOSI"], route: "tous_les_groupes", fils: false, description: "" }
        - { key: 2, name: "Recherche", roles: ["ROLE_GESTIONNAIRE", "ROLE_DOSI"], route: "", fils: [21, 22], description: "" }
        - { key: 21, name: "Rechercher un groupe", roles: ["ROLE_GESTIONNAIRE", "ROLE_DOSI"], route: "group_search", fils: false, description: "" }
        - { key: 22, name: "Rechercher une personne", roles: ["ROLE_GESTIONNAIRE", "ROLE_DOSI"], route: "user_search", fils: false, description: "" }
        - { key: 3, name: "Gestion des groupes", roles: ["ROLE_SUPER_ADMIN"], route: "", fils: [31, 32], description: "" }
        - { key: 31, name: "Cr&eacute;er un groupe", roles: ["ROLE_SUPER_ADMIN"], route: "group_create", fils: false, description: "" }
        - { key: 32, name: "Supprimer un groupe", roles: ["ROLE_SUPER_ADMIN"], route: "group_search", fils: false, description: "" }
        - { key: 4, name: "Aide", roles: ["ROLE_GESTIONNAIRE", "ROLE_DOSI"], route: "accueil", fils: false, description: "" }
        
        
#        - { key: 1, name: "Accueil", roles: ["ROLE_STUDENT","ROLE_STUDENT_MED","ROLE_ADMIN","ROLE_MANAGER","ROLE_VIEWER"], route: "accueil",fils: false,  description: "Retour &agrave; la page d'accueil de l'application", ico: "bundles/app/images/ico/16/home.png"  }

#        - { key: 5,  name: "MENU DE TEST NO ACCESS",     roles: ["ROLE_MENU2"],  route: "",       fils: false,  description: "Menu test no access...", showDisabled: true  }

 #       - { key: 4,  name: "TEST CAS",     roles: ["ROLE_MENU_CAS"],  route: "",       fils: [41,42,43,44] ,  description: "Menu CAS..."   }
 #       - { key: 41, name: "LOGIN",        roles: ["ROLE_MENU_CAS"],  route: "login",            fils: false,  description: "login", showDisabled: true  }
 #       - { key: 42, name: "Check",        roles: ["ROLE_MENU_CAS"],  route: "check_path",        fils: false,  description: "check"   }
 #       - { key: 43, name: "Logout",       roles: ["ROLE_MENU_CAS"],  route: "logout",           fils: false,  description: "logout"   }
 #       - { key: 44, name: "Logout_cas",   roles: ["ROLE_MENU_CAS"],  route: "logout_cas",           fils: false,  description: "logout cas"   }

 #      - { key: 1,  name: "MENU N&deg; 1 ",                roles: ["ROLE_MENU1","ROLE_USER"],  route: "homepage",      fils: [11,12,13,14,15,16,18,19],  description: "Menu Num&eacute;ro 1..."   }
 #       - { key: 11, name: "Sous-menu 1.1 sample 'Student'",  roles: ["ROLE_MENU1_1","ROLE_STUDENT"], route: "_demo_student",       fils: false,  description: "Ce sous-menu '1.1' permet..." }
 #       - { key: 12, name: "Sous-menu 1.2 sample 'Personal'", roles: ["ROLE_MENU1_2","ROLE_USER"], route: "_demo_personal",       fils: false,  description: "Ce sous-menu '1.2' permet..." }
 #       - { key: 13, name: " ", roles: "", route: "", fils: false, description: "" } 
 #       - { key: 14, name: "Sous-menu 1.3 sample css 'post-it'",        roles: ["ROLE_MENU1_3","ROLE_USER"], route: "_demo_postit",       fils: false,  description: "Ce sous-menu '1.3' permet..." }
 #       - { key: 15, name: "Sous-menu 1.4 sample css 'charte'",        roles: ["ROLE_MENU1_4","ROLE_USER"], route: "_demo_charte",       fils: false,  description: "Ce sous-menu '1.4' permet...", ico: "bundles/app/images/amu/AMU_ico.png"  }
 #       - { key: 16, name: "Sous-menu 1.5 colorPicker",        roles: ["ROLE_MENU1_4","ROLE_USER"], route: "_demo_colorpicker",       fils: false,  description: "Ce sous-menu '1.4' permet..." }
#        - { key: 17, name: "Sous-menu 1.4 ckeditor",        roles: ["ROLE_MENU1_4","ROLE_USER"], route: "_demo_ckeditor",       fils: false,  description: "Ce sous-menu '1.4' permet..." }
  #      - { key: 18, name: "Sous-menu 1.8 test PDF",        roles: ["ROLE_MENU1_4","ROLE_USER"], route: "_demo_pdf",       fils: false,  description: "Demo PDF", ico: 'bundles/app/images/ico/16/pdf.png'  }
  #      - { key: 19, name: "Sous-menu 1.9 user infos",        roles: ["ROLE_MENU1_4","ROLE_USER"], route: "_demo_infos",       fils: false,  description: "Demo infos User" }
        
 #       - { key: 2,  name: "MENU N&deg; 2",            roles: ["ROLE_MENU2"], route: "homepage",    fils: [20,21,22,23,24,25],  description: "Menu Num&eacute;ro 2 Tableaux...", ico: "bundles/app/images/amu/AMU_ico.png"  }
 #       - { key: 20, name: "Sous-menu 2-0 sample 'tablesorter'",   roles: ["ROLE_MENU2"], route: "_demo_table",       fils: false,  description: "Ce sous-menu '2.0' permet..." }
 #       - { key: 21, name: "Sous-menu 2-1 sample 'tablesorter6'",  roles: ["ROLE_MENU2"], route: "_demo_table1",       fils: false,  description: "Ce sous-menu '2.1' permet..." }
 #       - { key: 22, name: "Sous-menu 2-2 sample 'datatable'",     roles: ["ROLE_MENU2"], route: "_demo_table2",       fils: false,  description: "Ce sous-menu '2.2' permet..." }
 #       - { key: 23, name: " ", roles: "", route: "", fils: false, description: "" } 
 #       - { key: 24, name: "Sous-menu 2-3 (libell&eacute; plus long que les autres...)",   roles: ["ROLE_MENU23"], route: "_demo_charte",       fils: false,  description: "Ce sous-menu '2.3' permet..." }
 #       - { key: 25, name: "Sous-menu 2-4 sample 'highcharts'",   roles: ["ROLE_MENU2"], route: "_demo_highcharts",       fils: false,  description: "Ce sous-menu '2.4' permet...", ico: "bundles/app/images/ico/16/stats.png" }

 #       - { key: 3,  name: "MENU N&deg;3",   roles: ["ROLE_USER"],  route: "",    fils: [31],  description: ""   }
 #       - { key: 31,  name: "test config app2",   roles: ["ROLE_USER"],  route: "_demo_config2",    fils: false,  description: ""   }
       
#        - { key: 4,  name: "MENU N&deg;4",   roles: ["ROLE_USER"],  route: "_demo_student",    fils: false,  description: "Ce menu 'Fonctionnalit&eacute; N&deg;4'<br><br> Vous permettra de faire ceci ou cela...<hr>Mais il n'a <b><font color=red>pas de sous-menu...</font></b>"   }

#        - { key: 6,  name: "Liens", roles: ["ROLE_USER"], route: "",  url: "", fils: [61,62,63,64,65],  description: ""  }
#        - { key: 61, name: "Grouper", roles: ["ROLE_USER"], route: "",  url: "http://grouper.univ-amu.fr/grouper", fils: false,  description: ""  }
#        - { key: 62, name: " ", roles: ["ROLE_USER"], route: "",  url: "", fils: false,  description: ""  }
#        - { key: 64,  name: "Site de l'Universit&eacute;", roles: ["ROLE_USER"], route: "",  url: "http://www.univ-amu.fr", fils: false,  description: "Acc&eacute;s au site officiel..."  }
#        - { key: 65,  name: "Site de la D.O.S.I.", roles: ["ROLE_USER"], route: "",  url: "http://dosi.univ-amu.fr", fils: false,  description: "Acc&eacute;s au site de la D.O.S.I."  }
     
#        - { key: 7,  name: "Externes", roles: ["ROLE_EXTERNAL"], route: "",  url: "", fils: [71,72],  description: "" , showDisabled: true  }
#        - { key: 71,  name: "Test 1", roles: ["ROLE_EXTERNAL"], route: "_demo_ext_test1",  url: "", fils: false,  description: ""  }
#        - { key: 72,  name: "Test 2", roles: ["ROLE_EXTERNAL"], route: "_demo_ext_test2",  url: "", fils: false,  description: ""  }

 #       - { key: 8,  name: "Admin", roles: [ROLE_ADMIN,ROLE_SUPER_ADMIN], route: "",  url: "", fils: [81,82],  description: "", show_routes:["_demo_student"]   }
 #       - { key: 81,  name: "Test Ext1", roles: [ROLE_ADMIN,ROLE_SUPER_ADMIN], route: "_demo_ext_test1",  url: "", fils: false,  description: "", show_routes:["_demo_student"]   }
 #       - { key: 82,  name: "Test Ext2", roles: [ROLE_ADMIN,ROLE_SUPER_ADMIN], route: "_demo_ext_test2",  url: "", fils: false,  description: "", show_routes:["_demo_student"]   }
   
 #       - { key: 9, name: "TEST 'Student Access'",  roles: ["ROLE_MENU1_1","ROLE_STUDENT"], route: "_demo_student",       fils: false,  description: "Ce test permet..." }

 #       - { key: 'sep', name: " ", roles: "", route: "", fils: false, description: "" } 
        
 #       - { key: 1000, name: "RSS", roles: ["ROLE_STUDENT_MED"], route: "rssStudent",fils: false,  description: "Flux d'informations personnel", ico: "bundles/app/images/ico/16/rss.png"  }

twig:
     globals:
       app_menus: %menus%
       #app_menus_show_no_access: false
       app_no_access_tip: "Acc&egrave;s refus&eacute;|<center><font color=red><b>ACC&Egrave;S REFUS&Eacute;</b></center></font></br><b><i>Vous n'avez pas l'autorisation d'acc&egrave;der &agrave; cette fonctionalit&eacute;...</i></b>"
