## YAML Template.
---
parameters:

    amu_chartegraphique_title: "Groupie"
    amu_chartegraphique_auteur: "DOSI"
    amu_chartegraphique_apptitle: "Groupie"
    amu_chartegraphique_appslogan: "Gestion des groupes"
    amu_chartegraphique_appcontact: ""

twig:
    globals:
        auteur: '%amu_chartegraphique_auteur%'
        apptitle: '%amu_chartegraphique_apptitle%'
        appslogan: '%amu_chartegraphique_appslogan%'
        appcontact: '%amu_chartegraphique_appcontact%'
        title: '%amu_chartegraphique_title%'
